# Create Some Text


In [2]:
text = 'Chapter 1'


In [3]:
# Add Spaces Of Padding To The Left
format(text, '>20')

'           Chapter 1'

In [4]:
# Add Spaces Of Padding To The Right
format(text, '<20')


'Chapter 1           '

In [5]:
# Add Spaces Of Padding On Each Side
format(text, '^20')


'     Chapter 1      '

In [6]:
# Add * Of Padding On Each Side
format(text, '*^20')


'*****Chapter 1******'

# All Combinations For A List Of Objects


In [7]:
# Import combinations with replacements from itertools
from itertools import combinations_with_replacement


In [8]:
# Create a list of objects to combine
list_of_objects = ['warplanes', 'armor', 'infantry']


In [14]:
# Create an empty list object to hold the results of the loop
combinations = []

# Create a loop for every item in the length of list_of_objects, that,
for i in list(range(len(list_of_objects))):
    # Finds every combination (with replacement) for each object in the list
    combinations.append(combinations_with_replacement(list_of_objects, i+1))


In [10]:
# Flatten the list of iterators into a single list
combinations = [i for row in combinations for i in row]

# View the results
combinations


[('warplanes',),
 ('armor',),
 ('infantry',),
 ('warplanes', 'warplanes'),
 ('warplanes', 'armor'),
 ('warplanes', 'infantry'),
 ('armor', 'armor'),
 ('armor', 'infantry'),
 ('infantry', 'infantry'),
 ('warplanes', 'warplanes', 'warplanes'),
 ('warplanes', 'warplanes', 'armor'),
 ('warplanes', 'warplanes', 'infantry'),
 ('warplanes', 'armor', 'armor'),
 ('warplanes', 'armor', 'infantry'),
 ('warplanes', 'infantry', 'infantry'),
 ('armor', 'armor', 'armor'),
 ('armor', 'armor', 'infantry'),
 ('armor', 'infantry', 'infantry'),
 ('infantry', 'infantry', 'infantry')]

# Apply Operations Over Items In A List
Method 1: map()


In [15]:
# Create a list of casualties from battles
battleDeaths = [482, 93, 392, 920, 813, 199, 374, 237, 244]


In [16]:
# Create a function that updates all battle deaths by adding 100
def updated(x): return x + 100


In [17]:
# Create a list that applies updated() to all elements of battleDeaths
list(map(updated, battleDeaths))


[582, 193, 492, 1020, 913, 299, 474, 337, 344]

# Method 2: for x in y


In [18]:
# Create a list of deaths
casualties = [482, 93, 392, 920, 813, 199, 374, 237, 244]


In [19]:
# Create a variable where we will put the updated casualty numbers
casualtiesUpdated = []


In [20]:
# Create a function that for each item in casualties, adds 10
for x in casualties:
    casualtiesUpdated.append(x + 100)


In [21]:
# View casualties variables
casualtiesUpdated


[582, 193, 492, 1020, 913, 299, 474, 337, 344]

In [22]:
# Map the lambda function x() over casualties
list(map((lambda x: x + 100), casualties))


[582, 193, 492, 1020, 913, 299, 474, 337, 344]

# Applying Functions To List Items


In [23]:
regimentNames = ['Night Riflemen', 'Jungle Scouts', 'The Dragoons', 'Midnight Revengence', 'Wily Warriors']


In [24]:
# create a variable for the for loop results
regimentNamesCapitalized_f = []

# for every item in regimentNames
for i in regimentNames:
    # capitalize the item and add it to regimentNamesCapitalized_f
    regimentNamesCapitalized_f.append(i.upper())

# View the outcome
regimentNamesCapitalized_f


['NIGHT RIFLEMEN',
 'JUNGLE SCOUTS',
 'THE DRAGOONS',
 'MIDNIGHT REVENGENCE',
 'WILY WARRIORS']

In [25]:
capitalizer = lambda x: x.upper()


In [26]:
regimentNamesCapitalized_m = list(map(capitalizer, regimentNames)); regimentNamesCapitalized_m


['NIGHT RIFLEMEN',
 'JUNGLE SCOUTS',
 'THE DRAGOONS',
 'MIDNIGHT REVENGENCE',
 'WILY WARRIORS']

In [27]:
regimentNamesCapitalized_l = [x.upper() for x in regimentNames]; regimentNamesCapitalized_l


['NIGHT RIFLEMEN',
 'JUNGLE SCOUTS',
 'THE DRAGOONS',
 'MIDNIGHT REVENGENCE',
 'WILY WARRIORS']


# Arithmetic Basics



In [28]:
x = 6
y = 9


In [29]:
x + y


15

In [30]:
x - y


-3

In [31]:
x * y


54

In [32]:
x % y


6

In [33]:
x / y


0.6666666666666666

In [34]:
x // y


0

In [35]:
x ** y


10077696

In [36]:
(x + y) / x


2.5

In [42]:
#Classic divison of 3 by 5

3 / 5


0.6

In [40]:
#Floor divison of 3 by 5. This means it truncates any remainder down the its “floor”

3 // 5


0

# Assignment Operators


In [2]:
a = 2
b = 1
c = 0
d = 3


In [3]:
c = a + b
c


3

In [4]:
c += a
c


5

In [5]:
c -= a
c


3

In [6]:
c *= a
c


6

In [7]:
c /= a
c


3.0

In [8]:
d %= a
d


1

In [9]:
d **= a
d


1

In [10]:
d //= a
d



0

# Basic Operations With NumPy Array


In [11]:
# Import modules
import numpy as np

In [12]:
# Create an array
civilian_deaths = np.array([4352, 233, 3245, 256, 2394])
civilian_deaths


array([4352,  233, 3245,  256, 2394])

In [17]:
# Mean value of the array
civilian_deaths.mean()


2096.0

In [14]:
# Total amount of deaths
civilian_deaths.sum()


10480

In [15]:
# Smallest value in the array
civilian_deaths.min()


233

In [16]:
# Largest value in the array
civilian_deaths.max()


4352

# Breaking Up String Variables


In [18]:
variableName = 'This is a string.'


In [19]:
One, Two, Three = [1, 2, 3]


In [20]:
firstLetter, secondLetter, thirdLetter, fourthLetter = 'Bark'
firstLetter


'B'

In [21]:
secondLetter


'a'

In [22]:
thirdLetter


'r'

In [23]:
fourthLetter


'k'

In [24]:
firstNumber, secondNumber, thirdNumber, fourthNumber = '9485'
firstNumber

'9'

In [25]:
secondNumber


'4'

In [26]:
a, *b = 'spam'
a


's'

In [27]:
b


['p', 'a', 'm']

# Brute Force D20 Roll Simulator


In [28]:
import random


In [35]:
rolling = True


In [36]:
#Create a while loop that rolls until the first digit is 2 or less and the second digit is 10 or less


In [37]:
# while rolling is true
while rolling:
    # create x, a random number between 0 and 99
    x = random.randint(0, 99)
    # create y, a random number between 0 and 99
    y = random.randint(0, 99)
    # if x is less than 2 and y is between 0 and 10
    if x < 2 and 0 < y < 10:
        # Print the outcome
        print('You rolled a {0}{1}.'.format(x, y))
        # And set roll of False
        rolling = False
    # Otherwise
    else:
        # Try again
        print('Trying again.')


Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying again.
Trying

# Indexing And Slicing NumPy Arrays


In [38]:
# Import modules
import numpy as np

In [40]:
# Create a 2x2 array
battle_deaths = [[344, 2345], [253, 4345]]
deaths = np.array(battle_deaths)
deaths


array([[ 344, 2345],
       [ 253, 4345]])

In [41]:
# Select the top row, second item
deaths[0, 1]


2345

In [42]:
# Select the second column
deaths[:, 1]


array([2345, 4345])

In [43]:
# Select the second row
deaths[1, :]


array([ 253, 4345])

In [44]:
# Create an array of civilian deaths
civilian_deaths = np.array([4352, 233, 3245, 256, 2394])
civilian_deaths


array([4352,  233, 3245,  256, 2394])

In [45]:
# Find the index of battles with less than 500 deaths
few_civ_deaths = np.where(civilian_deaths < 500)
few_civ_deaths

(array([1, 3], dtype=int64),)

In [46]:
# Find the number of civilian deaths in battles with less than 500 deaths
civ_deaths = civilian_deaths[few_civ_deaths]
civ_deaths


array([233, 256])

In [47]:
# Iterate An Ifelse Over A List


In [48]:
word_list = ['Egypt', 'Watching', 'Eleanor']

vowels = ['A', 'E', 'I', 'O', 'U']


In [49]:
# for each item in the word_list,
for word in word_list:
    # if any word starts with e, where e is vowels,
    if any([word.startswith(e) for e in vowels]):
        # then print is valid,
        print('Is valid')
    # if not,    
    else:
        # print invalid
        print('Invalid')


Is valid
Invalid
Is valid


# Iterate Over Multiple Lists Simultaneously


In [50]:
names = ['James', 'Bob', 'Sarah', 'Marco', 'Nancy', 'Sally']
ages = [42, 13, 14, 25, 63, 23]

In [51]:
for name, age in zip(names, ages):
     print(name, age)


James 42
Bob 13
Sarah 14
Marco 25
Nancy 63
Sally 23


# Iterating Over Dictionary Keys


In [52]:
Officers = {'Michael Mulligan': 'Red Army',
            'Steven Johnson': 'Blue Army',
            'Jessica Billars': 'Green Army',
            'Sodoni Dogla': 'Purple Army',
            'Chris Jefferson': 'Orange Army'}


In [53]:
Officers


{'Michael Mulligan': 'Red Army',
 'Steven Johnson': 'Blue Army',
 'Jessica Billars': 'Green Army',
 'Sodoni Dogla': 'Purple Army',
 'Chris Jefferson': 'Orange Army'}

In [54]:
# Display all dictionary entries where the key doesn't start with 'Chris'
{keys : Officers[keys] for keys in Officers if not keys.startswith('Chris')}


{'Michael Mulligan': 'Red Army',
 'Steven Johnson': 'Blue Army',
 'Jessica Billars': 'Green Army',
 'Sodoni Dogla': 'Purple Army'}

In [55]:
# Lambda Functions


In [56]:
pipeline = [lambda x: x **2 - 1 + 5,
            lambda x: x **20 - 2 + 3,
            lambda x: x **200 - 1 + 4]


In [57]:
for f in pipeline:
    print(f(3))

13
3486784402
265613988875874769338781322035779626829233452653394495974574961739092490901302182994384699044004


# List All Files Of Certain Type In A Directory


In [58]:
import os


In [59]:
[x for x in os.listdir() if x.endswith(".ipynb")]


['Basic_python.ipynb']

In [60]:
# Logical Operations


In [61]:
x = 6
y = 9
z = 12


In [62]:
x or y


6

In [63]:
x and y


9

In [64]:
not x


False

In [65]:
x == y


False

In [66]:
x != y


True

In [67]:
1 < 2


True

In [68]:
2 <= 4


True

In [1]:
3 == 5


False

In [70]:
3 != 4


True

In [71]:
x < y < z


True

In [72]:
x < y and y < z


True

# Looping Over Two Lists


In [2]:
# Create a list of length 3:
armies = ['Red Army', 'Blue Army', 'Green Army']

# Create a list of length 4:
units = ['Red Infantry', 'Blue Armor','Green Artillery','Orange Aircraft']


In [3]:
# For each element in the first list,
for army, unit in zip(armies, units):
    # Display the corresponding index element of the second list:
    print(army, 'has the following options:', unit)


Red Army has the following options: Red Infantry
Blue Army has the following options: Blue Armor
Green Army has the following options: Green Artillery


# Mathematical Operations


In [4]:
import math


In [5]:
math.pi


3.141592653589793

In [6]:
math.e


2.718281828459045

In [7]:
math.sin(2 * math.pi / 180)


0.03489949670250097

In [8]:
2 ** 4, pow(2, 4)


(16, 16)

In [9]:
abs(-20)


20

In [10]:
min(3, 9, 10, 12)


3

In [11]:
max(3, 5, 10, 15)


15

In [12]:
math.floor(2.949)


2

In [15]:
math.ceil(32.09292)


33

In [14]:
int(3.292838)


3

In [16]:
round(2.943), round(2.499)


(3, 2)

In [18]:
round(2.569, 2)


2.57

# Cartesian Product


In [19]:
# import pandas as pd
import pandas as pd


In [20]:
# Create two lists
i = [1,2,3,4,5]
j = [1,2,3,4,5]


In [21]:
# List every single x in i with every single y (i.e. Cartesian product)
[(x, y) for x in i for y in j]


[(1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (3, 5),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4),
 (4, 5),
 (5, 1),
 (5, 2),
 (5, 3),
 (5, 4),
 (5, 5)]

In [25]:
# An alternative way to do the cartesian product

# import itertools
import itertools

# for two sets, find the the cartisan product
for i in itertools.product([1,2,3,4,5], [1,2,3,4,5]):
    # and print it
    print(i)


(1, 1)
(1, 2)
(1, 3)
(1, 4)
(1, 5)
(2, 1)
(2, 2)
(2, 3)
(2, 4)
(2, 5)
(3, 1)
(3, 2)
(3, 3)
(3, 4)
(3, 5)
(4, 1)
(4, 2)
(4, 3)
(4, 4)
(4, 5)
(5, 1)
(5, 2)
(5, 3)
(5, 4)
(5, 5)


# Mocking Functions


In [26]:
import unittest
+import mock
from math import exp


In [27]:

# Create a function,
def mock_function(x):
    # That returns a string.
    return 'This is not exp, but rather mock_function.'


In [28]:
# Create a test case,
class TestRandom(unittest.TestCase):
    # where math.exp (__main__.exp is because we imported the exp module from math)
    # math.exp is mocked (replaced) by mock_function,
    @mock.patch('__main__.exp', side_effect=mock_function)
    # now create a unit test that would only be true IF the exp(4) was being mocked
    # (so we can prove that math.exp is actually being mocked)
    def test_math_exp(self, mock_function):
        # assert that math.exp(4) is actually a string, which would only be the case
        # if math.exp was being mocked by mock_function
        assert exp(4) == 'This is not exp, but rather mock_function.'


In [30]:
unittest.main(argv=['ignored', '-v'], exit=False)


test_math_exp (__main__.TestRandom) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.002s

OK


# Chain Together Lists


In [31]:
from itertools import chain


In [32]:
# Create a list of allies
allies = ['Spain', 'Germany', 'Namibia', 'Austria']

# Create a list of enemies
enemies = ['Mexico', 'United Kingdom', 'France']


In [33]:
# For each country in allies and enemies
for country in chain(allies, enemies):
    # print the country
    print(country)


Spain
Germany
Namibia
Austria
Mexico
United Kingdom
France


# Nested For Loops Using List Comprehension


In [34]:
# Create two lists
squads = ["1st Squad", '2nd Squad', '3rd Squad']
regiments = ["51st Regiment", '15th Regiment', '12th Regiment']


In [35]:
# Create a tuple for each regiment in regiments, for each squad in sqauds
[(regiment, squad) for regiment in regiments for squad in squads ]


[('51st Regiment', '1st Squad'),
 ('51st Regiment', '2nd Squad'),
 ('51st Regiment', '3rd Squad'),
 ('15th Regiment', '1st Squad'),
 ('15th Regiment', '2nd Squad'),
 ('15th Regiment', '3rd Squad'),
 ('12th Regiment', '1st Squad'),
 ('12th Regiment', '2nd Squad'),
 ('12th Regiment', '3rd Squad')]

# Cleaning Text


In [36]:
# Create a list of three strings.
incoming_reports = ["We are attacking on their left flank but are losing many men.", 
               "We cannot see the enemy army. Nothing else to report.", 
               "We are ready to attack but are waiting for your orders."]


In [37]:
# import word tokenizer
from nltk.tokenize import word_tokenize

# Apply word_tokenize to each element of the list called incoming_reports
tokenized_reports = [word_tokenize(report) for report in incoming_reports]

# View tokenized_reports
tokenized_reports


[['We',
  'are',
  'attacking',
  'on',
  'their',
  'left',
  'flank',
  'but',
  'are',
  'losing',
  'many',
  'men',
  '.'],
 ['We',
  'can',
  'not',
  'see',
  'the',
  'enemy',
  'army',
  '.',
  'Nothing',
  'else',
  'to',
  'report',
  '.'],
 ['We',
  'are',
  'ready',
  'to',
  'attack',
  'but',
  'are',
  'waiting',
  'for',
  'your',
  'orders',
  '.']]

In [38]:
# Import regex
import re

# Import string
import string


regex = re.compile('[%s]' % re.escape(string.punctuation)) #see documentation here: http://docs.python.org/2/library/string.html

tokenized_reports_no_punctuation = []

for review in tokenized_reports:
    
    new_review = []
    for token in review: 
        new_token = regex.sub(u'', token)
        if not new_token == u'':
            new_review.append(new_token)
    
    tokenized_reports_no_punctuation.append(new_review)
    
tokenized_reports_no_punctuation


[['We',
  'are',
  'attacking',
  'on',
  'their',
  'left',
  'flank',
  'but',
  'are',
  'losing',
  'many',
  'men'],
 ['We',
  'can',
  'not',
  'see',
  'the',
  'enemy',
  'army',
  'Nothing',
  'else',
  'to',
  'report'],
 ['We',
  'are',
  'ready',
  'to',
  'attack',
  'but',
  'are',
  'waiting',
  'for',
  'your',
  'orders']]

In [39]:

from nltk.corpus import stopwords

tokenized_reports_no_stopwords = []
for report in tokenized_reports_no_punctuation:
    new_term_vector = []
    for word in report:
        if not word in stopwords.words('english'):
            new_term_vector.append(word)
    tokenized_reports_no_stopwords.append(new_term_vector)
            
tokenized_reports_no_stopwords


[['We', 'attacking', 'left', 'flank', 'losing', 'many', 'men'],
 ['We', 'see', 'enemy', 'army', 'Nothing', 'else', 'report'],
 ['We', 'ready', 'attack', 'waiting', 'orders']]

# Nesting Lists


In [1]:
# Create a list of three nested lists, each with three items
state_regions = [['California', 'Oregon', 'Washington'],
        ['Texas','Georgia','Alabama'],
        ['Maine','Vermont','New York']]


In [2]:
# View the list
state_regions


[['California', 'Oregon', 'Washington'],
 ['Texas', 'Georgia', 'Alabama'],
 ['Maine', 'Vermont', 'New York']]

In [3]:
# Print the second list's third item
state_regions[1][2]


'Alabama'

# Compare Two Dictionaries


In [4]:
importers = {'El Salvador' : 1234,
             'Nicaragua' : 152,
             'Spain' : 252
            }

exporters = {'Spain' : 252,
             'Germany' : 251,
             'Italy' : 1563
             }


In [5]:
# Find the intersection of importers and exporters
importers.keys() & exporters.keys()


{'Spain'}

In [6]:
# Find the difference between importers and exporters
importers.keys() - exporters.keys()


{'El Salvador', 'Nicaragua'}

In [7]:
# Find countries where the amount of exports matches the amount of imports
importers.items() & exporters.items()


{('Spain', 252)}

# Numpy Array Basics


In [1]:
# Import modules
import numpy as np


In [2]:
# Create a list
battle_deaths = [3246, 326, 2754, 2547, 2457, 3456]
battle_deaths


[3246, 326, 2754, 2547, 2457, 3456]

In [3]:
# Create an array from numpy
deaths = np.array(battle_deaths)
deaths


array([3246,  326, 2754, 2547, 2457, 3456])

In [4]:
# Create an array of zeros
defectors = np.zeros(6)
defectors


array([0., 0., 0., 0., 0., 0.])

In [5]:
# Create a range from 0 to 100
zero_to_99 = np.arange(0, 100)
zero_to_99


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
# Create 100 ticks between 0 and 1
zero_to_1 = np.linspace(0, 1, 100)
zero_to_1


array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747